### ISSUE TITLE
Cannot reproduce minimal example

### ISSUE THREAD

**Issue by jooyoungseo** [julianna-langston/chart2music#17]
Thanks for working on and releasing such a great open-source project!

I was attempting to reproduce a minimal example using the instruction provided in readme. However, the following code does not produce any sonification layers. Could you please help me better understand what's wrong with my code below?

```html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <script src="https://cdn.jsdelivr.net/npm/chart2music"></script>
</head>

<body>

    <img src="mychart.png" id="MyChart" />

    <script>
        c2mChart({
            type: "bar",
            element: document.getElementById("MyChart"),
            data: [1, 2, 3]
        });
    </script>
</body>

</html>
```

**Comment by julianna-ciq** [comment]
Sorry, I didn't realize our example got out of sync with how we bundled our module. Here is the correct way to call it now, and I will look into getting the bundler working more effectively:

```
<script>
        c2mChart.c2mChart({
            type: "bar",
            element: document.getElementById("MyChart"),
            data: [1, 2, 3]
        });
    </script>
```

**Comment by julianna-ciq** [comment]
Does that work for you?

**Comment by julianna-ciq** [comment]
Please ignore the above comments; I pushed a fix in v1.3.0.

Do you mind checking and confirming that it works for you now?

**Comment by jooyoungseo** [comment]
Thanks for investigating this issue. I have confirmed the example works only with the explicit namespace just like `c2mChart.c2mChart`. However, it still does not work with the single function name.

**Comment by jooyoungseo** [comment]
Also, I have just noticed another issue. I will create this separately.

**Comment by jooyoungseo** [comment]
Okay, the following cdn now works without the module name:

```html
<script src="https://cdn.jsdelivr.net/npm/chart2music"></script>
```

**Comment by jooyoungseo** [comment]
However, the following cdn has not been updated (the latest version). This does not work without the module name:

```html
<script src="https://cdn.jsdelivr.net/npm/chart2music@latest/dist/index.min.js"></script>
```

**Comment by jooyoungseo** [comment]
@julianna-ciq -- What's the different purpose between these cdn? I am asking this because some documents recommend using one without the latest prefix and some docs demonstrate with the latest cdn. Documenting the difference would be helpful for the users.

**Comment by julianna-ciq** [comment]
jsDelivr sometimes takes a while to clear its cache for all of the tagged versions of scripts. (Any versions that include an `@` symbol.)
Using the `@latest` tag says that you want the latest version. I believe this distinguishes from beta releases or something, but I'm not sure. I liked using it for a while because it made explicit that it would always be using the latest version, as opposed to a specific version. So far, if you leave it without a tag, or you use the `@latest` tag, you should get the same version of Chart2Music (after the delay for jsDelivr's cache to update).

Either way, you're right, I was including inconsistent code about how to reference the CDN. I've updated the docs in the repo to be consistent. I won't have a chance to deploy the changes to chart2music.com for a few days, but the repo is up-to-date.

Please let me know if you find any other bugs or doc issues!

**Comment by jooyoungseo** [comment]
Thanks for the explanation, @julianna-ciq . I hope that you don't mind me asking a follow-up question. In order to work with a local version of c2m, what file do I need to include in `<script>` tag? I assume it's `./dist/index.js`, but it did not work on my end. How do I obtain the minified and local version of the cdn?

**Comment by julianna-ciq** [comment]
If you just have an .html file, I guess you could just download jsDelivr's minified file. So, I'd go to this page:
https://cdn.jsdelivr.net/npm/chart2music
and just save with Ctrl + S. By default, it would save to my Downloads folder as chart2music.js. Then, I'd just reference it with something like
`<script src="./chart2music.js"></script>`

**Comment by jooyoungseo** [comment]
Thanks! That workaround works. However, the local version does not work with the directly embedded raw svg objects. It works for other formats, such as png, object, etc. Only cdn works for the raw svg.

**Comment by julianna-ciq** [comment]
The third line of the downloaded version should say:
```
Original file: /npm/chart2music@1.3.1/dist/index.js
```

Can you confirm it says that for me?

**Comment by jooyoungseo** [comment]
With v1.3.1, it's now working as expected! Thanks! Mine was v1.3.0 and had to redownload after refreshing my browser cache with (Ctrl+F5).
